function escapeHtml(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}

function hashString(s){let h=0;for(let i=0;i<s.length;i++){h=((h<<5)-h)+s.charCodeAt(i);h|=0}return Math.abs(h)}
function rng(seed){return function(){let t=seed+=0x6D2B79F5;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296}}
function shuffle(a,seed){const r=[...a],rand=rng(seed);for(let i=r.length-1;i>0;i--){const j=Math.floor(rand()*(i+1));[r[i],r[j]]=[r[j],r[i]]}return r}
function isoWeek(d){const x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));const day=x.getUTCDay()||7;x.setUTCDate(x.getUTCDate()+4-day);const start=new Date(Date.UTC(x.getUTCFullYear(),0,1));return Math.ceil((((x-start)/86400000)+1)/7)}
function key(mode){const d=new Date();if(mode==="weekly")return`weekly-${d.getFullYear()}-W${isoWeek(d)}`;return`daily-${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`}
function renderFeaturedCast(){const grid=document.getElementById("featuredCastGrid");if(!grid)return;const cfg=window.FEATURE_CONFIG||{mode:"daily",count:3};const title=document.getElementById("featuredTitle"),k=document.getElementById("featuredKicker");if(cfg.mode==="weekly"){if(title)title.textContent="本週推薦";if(k)k.textContent="WEEKLY FEATURED CAST"}const candidates=(window.allCasts||[]).filter(c=>c.status==="available");const picked=shuffle(candidates,hashString(key(cfg.mode))).slice(0,Math.min(cfg.count,candidates.length));grid.innerHTML=picked.map(c=>`<article class="card staff-card"><div class="staff-img" style="--cast-image:url('${escapeHtml(c.image)}')">${escapeHtml(c.image)}</div><div class="staff-body"><h3>${escapeHtml(c.name)}</h3><p>${escapeHtml(c.shortDesc||c.desc)}</p><div class="tag-row">${(c.tags||[]).map(t=>`<span class="tag">${escapeHtml(t)}</span>`).join("")}</div><p>「${escapeHtml(c.quote||"")}」</p><div class="cta-row"><a class="btn primary" href="booking.html?cast=${encodeURIComponent(c.name)}">指名預約</a><a class="btn" href="cast.html">完整介紹</a></div></div></article>`).join("")}
renderFeaturedCast();
